import "./globals.css";
import NavBar from "@/components/NavBar";
import { Source_Sans_3 } from "next/font/google";

const sourceSans = Source_Sans_3({ subsets: ["latin"] });

export const metadata = {
  title: "Plumeria Archive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sourceSans.className}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
